# -*- coding: utf-8 -*-
"""ejemplo_st.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ejL3hqmzPwKHCrCzpgEm1eV2AyP8EF6B
"""

import streamlit as st

st.write('Hello,World:sunglasses:')